use bdExerc01

insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Dio Brando','BH',22,1)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Kars','SP',412,8)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Esidici','AC',322,5)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Wamuu','AC',250,0)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('DIO','RJ',122,1)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Kira Yoshikage','CE',33,0)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Diavolo','RS',29,1)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Pucci','AM',32,0)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Diego Brando','ES',21,0)
insert into tbFunc(nome_func,uf,idade,qtde_filhos)
values('Funny Valentyne','ES',28,1)

insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Designer',2500.00,7,5,'não',1)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Gerente',3000.00,350,254,'sim',2)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Analista',820.00,200,76,'não',3)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Analista',820.00,100,42,'não',4)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Programador',7500.00,78,70,'sim',5)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Programador',1100,16,4,'sim',6)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Gerente',12000.00,20,20,'sim',7)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Analista',700.00,16,14,'não',8)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Designer',750.69,12,4,'não',9)
insert into tbFuncional(cargo,salario,tempo_empresa,tempo_cargo,sindicalizado,codFunc)
values('Designer',700.00,12,9,'sim',10)

select * from tbFunc
select * from tbFuncional